[features]
seeds = false
skip-lint = false
[programs.testnet]
disk3 = "Disk39nVau5sgCmr6oJuKdfg2Nc5VQpXgd5C4ztSt7Vd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/ttang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
